### ISSUE TITLE
dependency environment issue

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#178]
hey,

this is working for `host-toolchain` (compat), but not for `target-toolchain` (cross):

```
depends:
    - environment:
          CXXFLAGS: "$CXXFLAGS something"
      depends:
          - libs....
```
