### ISSUE TITLE
def hostArch(args, **options): on x86_64 with aarch64 sandbox

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#36]
Hi,

if I call VAR: "$(host-arch)" in an aarch64 sandbox on a x86_64 host, the result is "x86_64", but expected "arm64" IMO.
What do u expect?

BR.

**Comment by jkloetzke** [comment]
Actually "x86_64" because your host is exactly that. This function should tell the native architecture of the host. You could have many different architectrures simultaneously in the sandbox given the proper qemu binaries. It wouldn't make sense to report all of them.

**Comment by mahaase** [comment]
what is the correct way to get the architecture of the build-host? that is mostly the arch-value we would need, e.g. in openssl recipe. the arch of the real host isn't interesting, if I build in an aarch64 sandbox, is it?

**Comment by jkloetzke** [comment]
You must set some variable with your provided sandbox. The build host architecture is truly reported by  "$(host-arch)". If you use a sandbox that contains a statically linked x86_64 qemu which can execute aarch64 binaries then this is nothing that can be detected from the outside. Your recipe that provides the sandbox must provide this information instead:

```yaml
provideSandbox:
    paths: ["/bin", "/usr/bin"]
    environment:
        ARCH: "arm64"
        AUTOCONF_BUILD: "aarch64-linux-gnu"
        AUTOCONF_HOST: "aarch64-linux-gnu"
```

Iff the sandbox is used then these variables will replace whatever was determined by `default.yaml`.
