### ISSUE TITLE
FeatureRequest: recipe override

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/basement#62]
hey, 

in the current basement, the gcc version 9 is used. this is a show-stopper for our projects.
we use CUDA for AGX embedded targets. currently cuda 10.2 is supported. 
this cuda version is limited to gcc version 8.

https://gist.github.com/ax3l/9489132

the embedded targets are currently limited to ubuntu 18 lts. 
so the libc version is older than the one used in basement. 
that is also net the best situation.

but i also won't fork everything, just because of one recipe?!

**Comment by daxcore** [comment]
this feature is not necessary so far :D
this one works for me:

```
scmOverrides:
  - match:
      url: "*gcc*9.2.0*"
    replace:
      url:
        pattern: "9.2.0"
        replacement: "8.4.0"
    set:
      digestSHA256: e30a6e52d10e1f27ed55104ad233c30bd1e99cfb5ff98ab022dc941edd1b2dd4
```
